# Copyright (c) 2008 Yahoo! Inc.
#
# Originally written by Jan Schaumann <jschauma@yahoo-inc.com> in July 2008.
#
# A Makefile to run all tests in this directory.

all:	py

py:
	@for p in *.py; do						\
		python $$p;						\
	done
